// action types
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_TASK = 'ADD_TASK'
export const TOGGLE_TASK = 'TOGGLE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const SIGN_IN = 'SIGN_IN'
export const INIT_ACCOUNT = 'INIT_ACCOUNT'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
